"""empty message

Revision ID: 62905d54a8ba
Revises: None
Create Date: 2019-03-27 15:36:14.443472

"""

# revision identifiers, used by Alembic.
revision = '62905d54a8ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post')
    # ### end Alembic commands ###
